require 'erb'
require 'yaml'
require 'ipaddr'
require 'thor'

require 'kite/version'
require 'kite/helpers'
require 'kite/error'

require 'kite/base'
require 'kite/render'
require 'kite/generate'
require 'kite/user_tasks_autoload'
require 'kite/core'
require 'kite/cloud'
